source: src

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/coming_soon
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock

plugins:
  - jekyll-assets
  - jekyll-sitemap

ga_analytics: # Add Google Analytics tracking code

social:
  facebook: Sudore-Express-327004091346998
  instagram: sudoreexpress

name: Sudore Express

permalink: pretty

url: https://sudore.co # Add your site url
